"""empty message

Revision ID: 4cda12cdbba9
Revises: 
Create Date: 2021-12-05 11:11:05.696553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cda12cdbba9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Unicode(length=128), nullable=True),
    sa.Column('receiver', sa.Unicode(length=128), nullable=True),
    sa.Column('body', sa.Unicode(length=8196), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=True),
    sa.Column('sent', sa.Integer(), nullable=True),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('bold', sa.Boolean(), nullable=True),
    sa.Column('italic', sa.Boolean(), nullable=True),
    sa.Column('underline', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Message')
    # ### end Alembic commands ###
